# configuration for https://github.com/sagiegurari/cargo-make

[config]
skip_core_tasks = true

[env]
ALL_FEATURES_FLAG = "--features=vsock"

[tasks.default]
alias = "ci"

[tasks.ci]
description = "Run continuous integration tasks"
dependencies = ["lint-style", "clippy", "check", "test"]

[tasks.lint-style]
description = "Lint code style (formatting, typos, docs)"
dependencies = ["lint-format", "lint-typos", "lint-docs"]

[tasks.lint-format]
description = "Lint code formatting"
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--all", "--check"]

[tasks.format]
description = "Fix code formatting"
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--all"]

[tasks.lint-typos]
description = "Run typo checks"
install_crate = { crate_name = "typos-cli", binary = "typos", test_arg = "--version" }
command = "typos"

[tasks.lint-docs]
description = "Check documentation for errors and warnings"
toolchain = "nightly"
command = "cargo"
args = [
  "rustdoc",
  "--no-default-features",
  "${ALL_FEATURES_FLAG}",
  "--",
  "-Zunstable-options",
  "--check",
  "-Dwarnings",
]

[tasks.check]
description = "Check code for errors and warnings"
command = "cargo"
args = [
  "check",
  "--all-targets",
  "--no-default-features",
  "${ALL_FEATURES_FLAG}",
]

[tasks.build]
description = "Compile the project"
command = "cargo"
args = [
  "build",
  "--all-targets",
  "--no-default-features",
  "${ALL_FEATURES_FLAG}",
]

[tasks.clippy]
description = "Run Clippy for linting"
command = "cargo"
args = [
  "clippy",
  "--all-targets",
  "--tests",
  "--benches",
  "--no-default-features",
  "${ALL_FEATURES_FLAG}",
  "--",
  "-D",
  "warnings",
]

[tasks.install-nextest]
description = "Install cargo-nextest"
install_crate = { crate_name = "cargo-nextest", binary = "cargo-nextest", test_arg = "--help" }

[tasks.test]
description = "Run tests"
run_task = { name = ["test-lib", "test-doc"] }

[tasks.test-lib]
description = "Run default tests"
dependencies = ["install-nextest"]
command = "cargo"
args = [
  "nextest",
  "run",
  "--all-targets",
  "--no-default-features",
  "${ALL_FEATURES_FLAG}",
]

[tasks.test-doc]
description = "Run documentation tests"
command = "cargo"
args = ["test", "--doc", "--no-default-features", "${ALL_FEATURES_FLAG}"]

[tasks.coverage]
description = "Generate code coverage report"
command = "cargo"
args = [
  "llvm-cov",
  "--lcov",
  "--output-path",
  "target/lcov.info",
  "--no-default-features",
  "${ALL_FEATURES_FLAG}",
]
